refresh_seconds: 5
ssh:
  connect_timeout: 3
  key_file: /root/.ssh/id_ed25519
  known_hosts_file: /root/.ssh/known_hosts

nodes:
  - name: Pi-01-6
    host: 192.168.1.10
    user: root
  - name: Pi-02-8
    host: 192.168.1.11
    user: root
  - name: Pi-03-5
    host: 192.168.1.12
    user: root

vrrp:
  - name: DNS
    vip: 192.168.1.100
    nodes: [Pi-01-6, Pi-02-8, Pi-03-5]
  - name: Caddy
    vip: 192.168.1.101
    nodes: [Pi-01-6, Pi-02-8]
  - name: Vaultwarden
    vip: 192.168.1.102
    nodes: [Pi-01-6, Pi-02-8]
