package config
import("fmt";"os";"gopkg.in/yaml.v3")
type Config struct{RefreshSeconds int `yaml:"refresh_seconds"`;SSH SSHConfig `yaml:"ssh"`;Notifications Notifications `yaml:"notifications"`;Nodes []Node `yaml:"nodes"`;VRRP []VRRP `yaml:"vrrp"`}
type SSHConfig struct{ConnectTimeout int `yaml:"connect_timeout"`;KeyFile string `yaml:"key_file"`;KnownHostsFile string `yaml:"known_hosts_file"`}
type Notifications struct{NodeDown NodeDown `yaml:"node_down"`;SMTP SMTP `yaml:"smtp"`;Telegram Telegram `yaml:"telegram"`}
type NodeDown struct{Enabled bool `yaml:"enabled"`;FailuresBeforeAlert int `yaml:"failures_before_alert"`;RecoveryMail bool `yaml:"recovery_mail"`}
type SMTP struct{Enabled bool `yaml:"enabled"`;Host string `yaml:"host"`;Port int `yaml:"port"`;Username string `yaml:"username"`;Password string `yaml:"password"`;From string `yaml:"from"`;To []string `yaml:"to"`;StartTLS bool `yaml:"starttls"`}
type Telegram struct{Enabled bool `yaml:"enabled"`;BotToken string `yaml:"bot_token"`;ChatID string `yaml:"chat_id"`}
type Node struct{Name string `yaml:"name" json:"name"`;Host string `yaml:"host" json:"host"`;User string `yaml:"user" json:"user"`}
type VRRP struct{Name string `yaml:"name" json:"name"`;VIP string `yaml:"vip" json:"vip"`;Nodes []string `yaml:"nodes" json:"nodes"`}
func Load(path string)(*Config,error){data,err:=os.ReadFile(path);if err!=nil{return nil,fmt.Errorf("read config: %w",err)};var c Config;if err:=yaml.Unmarshal(data,&c);err!=nil{return nil,fmt.Errorf("parse config: %w",err)};if c.RefreshSeconds<=0{c.RefreshSeconds=5};if c.SSH.ConnectTimeout<=0{c.SSH.ConnectTimeout=3};if c.Notifications.NodeDown.FailuresBeforeAlert<=0{c.Notifications.NodeDown.FailuresBeforeAlert=3};if c.Notifications.SMTP.Port<=0{c.Notifications.SMTP.Port=587};if err:=c.Validate();err!=nil{return nil,err};return &c,nil}
func(c *Config)Validate()error{seen:=map[string]struct{}{};for _,n:=range c.Nodes{if n.Name==""||n.Host==""||n.User==""{return fmt.Errorf("node name, host and user are required")};if _,ok:=seen[n.Name];ok{return fmt.Errorf("duplicate node %q",n.Name)};seen[n.Name]=struct{}{}};for _,v:=range c.VRRP{if v.Name==""||v.VIP==""{return fmt.Errorf("VRRP name and VIP are required")};for _,name:=range v.Nodes{if _,ok:=seen[name];!ok{return fmt.Errorf("VRRP %q references unknown node %q",v.Name,name)}}};if c.Notifications.SMTP.Enabled&&(c.Notifications.SMTP.Host==""||c.Notifications.SMTP.From==""||len(c.Notifications.SMTP.To)==0){return fmt.Errorf("smtp host, from and at least one recipient are required when SMTP is enabled")};if c.Notifications.Telegram.Enabled&&(c.Notifications.Telegram.BotToken==""||c.Notifications.Telegram.ChatID==""){return fmt.Errorf("telegram bot_token and chat_id are required when Telegram is enabled")};return nil}
