package main
import("context";"encoding/json";"log/slog";"net/http";"os";"os/signal";"strconv";"syscall";"time";"github.com/brainscan1980/Keepalived-Monitor/internal/config";"github.com/brainscan1980/Keepalived-Monitor/internal/monitor";"github.com/brainscan1980/Keepalived-Monitor/internal/storage")
var version="dev"
type healthResponse struct{Status string `json:"status"`;Version string `json:"version"`}
func main(){logger:=slog.New(slog.NewTextHandler(os.Stdout,nil));cfg,err:=config.Load(getenv("CONFIG_FILE","/app/config/config.yml"));if err!=nil{logger.Error("configuration failed","error",err);os.Exit(1)};store,err:=storage.Open(getenv("DB_FILE","/app/data/history.db"));if err!=nil{logger.Error("database failed","error",err);os.Exit(1)};defer store.Close();ctx,cancelMonitor:=context.WithCancel(context.Background());defer cancelMonitor();mon:=monitor.New(cfg,logger,store);go mon.Run(ctx);mux:=http.NewServeMux();mux.HandleFunc("GET /healthz",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,healthResponse{"ok",version})});mux.HandleFunc("GET /api/v1/status",func(w http.ResponseWriter,r *http.Request){s:=mon.Snapshot();writeJSON(w,200,map[string]any{"status":"ok","version":version,"refresh_seconds":cfg.RefreshSeconds,"nodes":s.Nodes,"vrrp":s.VRRP,"updated":s.Updated})});mux.HandleFunc("GET /api/v1/events",func(w http.ResponseWriter,r *http.Request){events,e:=store.Events(limit(r));if e!=nil{writeJSON(w,500,map[string]any{"ok":false,"error":"event history unavailable"});return};writeJSON(w,200,map[string]any{"ok":true,"events":events})});mux.HandleFunc("GET /api/v1/incidents",func(w http.ResponseWriter,r *http.Request){items,e:=store.Incidents(limit(r));if e!=nil{logger.Error("read incidents failed","error",e);writeJSON(w,500,map[string]any{"ok":false,"error":"incident history unavailable"});return};writeJSON(w,200,map[string]any{"ok":true,"incidents":items})});addr:=getenv("LISTEN_ADDR",":8080");srv:=&http.Server{Addr:addr,Handler:requestLogger(logger,mux),ReadHeaderTimeout:5*time.Second,ReadTimeout:15*time.Second,WriteTimeout:30*time.Second,IdleTimeout:60*time.Second};go func(){logger.Info("Keepalived Monitor Go starting","addr",addr,"version",version);if err:=srv.ListenAndServe();err!=nil&&err!=http.ErrServerClosed{logger.Error("HTTP server failed","error",err);os.Exit(1)}}();stop:=make(chan os.Signal,1);signal.Notify(stop,syscall.SIGINT,syscall.SIGTERM);<-stop;cancelMonitor();shutdownCtx,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();_=srv.Shutdown(shutdownCtx)}
func limit(r *http.Request)int{n:=50;if raw:=r.URL.Query().Get("limit");raw!=""{if x,e:=strconv.Atoi(raw);e==nil{n=x}};return n}
func getenv(n,f string)string{if v:=os.Getenv(n);v!=""{return v};return f}
func writeJSON(w http.ResponseWriter,s int,v any){w.Header().Set("Content-Type","application/json; charset=utf-8");w.WriteHeader(s);_=json.NewEncoder(w).Encode(v)}
func requestLogger(l *slog.Logger,n http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){t:=time.Now();n.ServeHTTP(w,r);l.Info("request","method",r.Method,"path",r.URL.Path,"duration",time.Since(t))})}
